webdriver.driver = "chrome"
webdriver.base.url = "https://automationexercise.com"
webdriver.autodownload = true

serenity.project.name = "AUTO_FRONT_POM_FACTORY - Front POM Page Factory"
serenity.take.screenshots = FOR_EACH_ACTION

chrome.switches = "--start-maximized;--disable-gpu;--remote-allow-origins=*"
